version: '3.9'

services:
  db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${PRE_ORDER_DATABASE_PASSWORD}
      - MYSQL_DATABASE=msa
      - MYSQL_USER=${PRE_ORDER_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${PRE_ORDER_DATABASE_PASSWORD}
    networks:
      - test_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6370:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - test_network

networks:
  test_network:
    driver: bridge