version: '3.9'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${secrets.PRE_ORDER_DATABASE_PASSWORD}
      - MYSQL_DATABASE=msa
      - MYSQL_USER=${secrets.PRE_ORDER_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${secrets.PRE_ORDER_DATABASE_PASSWORD}
    networks:
      - db
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - 6370:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=${secrets.PRE_ORDER_DATABASE_PASSWORD}
      - MYSQL_DATABASE=msa
      - MYSQL_USER=${secrets.PRE_ORDER_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${secrets.PRE_ORDER_DATABASE_PASSWORD}
    networks:
      - db

networks:
  db: