version: '3.9'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${PRE_ORDER_DATABASE_PASSWORD}
      - MYSQL_DATABASE=msa
      - MYSQL_USER=${PRE_ORDER_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${PRE_ORDER_DATABASE_PASSWORD}
    networks:
      - db

networks:
  db: